server:
  port: 8081

spring:
  profiles:
    active: dev

---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod


#person:
#  lastname: hello
#  age: 11
#  boss: false
#  birth: 2020/2/2
#  maps: {k1: v1,k2: v2}
#  lists:
#    - zhangsan
#    - lisi
#  dog:
#    name: gougou
#    age: 1