server:
  port: 8080

eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载平衡
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
